import express from 'express';
import authToken from '../../middleware/auth/auth.middleware';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import createComment from '../../service/impl/comment/createComment/createComment.impl';
import { commentSchema, updateCommentSchema } from '../../utils/validator';
import showComments from '../../service/impl/comment/showComments/showComments.impl';
import showComment from '../../service/impl/comment/showComment/showComment.impl';
import updateComment from '../../service/impl/comment/updateComment/updateComment.impl';
const router = express.Router();
router.post('/create-comment', authToken, globalValidator(commentSchema), createComment);
router.get('/show-comments', authToken, showComments);
router.get('/show-comment/:id', authToken, showComment);
router.put('/update-content-comment/:id', authToken, globalValidator(updateCommentSchema), updateComment);
export default router;