import express from 'express';
import authToken from '../../middleware/auth/auth.middleware';
import createProfile from '../../service/impl/profile/createProfile/createProfile.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { profileSchema, updateProfileSchema } from '../../utils/validator';
import showProfiles from '../../service/impl/profile/showProfiles/showProfiles.impl';
import showProfile from '../../service/impl/profile/showProfile/showProfile.impl';
import updateProfile from '../../service/impl/profile/updateProfile/updateProfile.impl';
const router = express.Router();
router.post('/create-profile', authToken, globalValidator(profileSchema), createProfile);
router.get('/show-profiles', authToken, showProfiles);
router.get('/show-profile/:id', authToken, showProfile);
router.put('/update-profile/:id', authToken, globalValidator(updateProfileSchema), updateProfile);
export default router;