import express from 'express';
import authToken from '../../middleware/auth/auth.middleware';
import sendContactMessage from '../../service/impl/contact/sendContactMessage/sendContactMessage.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { contactSchema, updateContactSchema } from '../../utils/validator';
import showContactMessages from '../../service/impl/contact/showContactMessages/showContactMessages.impl';
import showContactMessage from '../../service/impl/contact/showContactMessage/showContactMessage.impl';
import updateContactMessage from '../../service/impl/contact/updateContactMessage/updateContactMessage.impl';
import deleteContactMessage from '../../service/impl/contact/deleteContactMessage/deleteContactMessage.impl';
const router = express.Router();
router.post('/send-contact-message', authToken, globalValidator(contactSchema), sendContactMessage);
router.get('/show-contact-messsages', authToken, showContactMessages);
router.get('/show-contact-message/:id', authToken, showContactMessage);
router.put('/update-contact-message/:id', authToken, globalValidator(updateContactSchema), updateContactMessage);
router.delete('/delete-contact-message/:id', authToken, deleteContactMessage);
export default router;