import express from 'express';
import authToken from '../../middleware/auth/auth.middleware';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { mediaSchema } from '../../utils/validator';
import showMediaContents from '../../service/impl/media/showMedias/showMedias.impl';
import createMediaContent from '../../service/impl/media/createMedia/createMedia.impl';
const router = express.Router();
router.post('/create-media-content', authToken, globalValidator(mediaSchema), createMediaContent);
router.get('/show-media-contents', authToken, showMediaContents);
export default router;