import express from 'express';
import authToken from '../../middleware/auth/auth.middleware';
import createRole from '../../service/impl/role/createRole/createRole.impl';
import globalValidator from '../../middleware/globalValidator/globalValidator';
import { roleSchema, updateRoleSchema } from '../../utils/validator';
import showRoles from '../../service/impl/role/showRoles/showRoles.impl';
import showRole from '../../service/impl/role/showRole/showRole.impl';
import updateRole from '../../service/impl/role/updateRole/updateRole.impl';
const router = express.Router();
router.post('/create-role', authToken, globalValidator(roleSchema), createRole);
router.get('/show-roles', authToken, showRoles);
router.get('/show-role/:id', authToken, showRole);
router.put('/update-role/:id', authToken, globalValidator(updateRoleSchema), updateRole);
export default router;